# Generated by Django 5.0.14 on 2026-07-27 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('soc_percent', models.FloatField(blank=True, null=True)),
                ('estimation_method', models.CharField(choices=[('OCV', 'Tension a vide'), ('COULOMB', 'Comptage coulometrique'), ('BMS', 'Systeme de gestion de batterie'), ('UNKNOWN', 'Inconnu')], default='UNKNOWN', max_length=10)),
                ('uncertainty_percent', models.FloatField(blank=True, null=True)),
                ('estimation_reason', models.TextField(blank=True)),
                ('voltage_v', models.FloatField(blank=True, null=True)),
                ('current_a', models.FloatField(blank=True, null=True)),
                ('temperature_celsius', models.FloatField(blank=True, null=True)),
                ('direction', models.CharField(choices=[('CHARGE', 'En charge'), ('DISCHARGE', 'En decharge'), ('IDLE', 'Au repos'), ('UNKNOWN', 'Inconnu')], default='UNKNOWN', max_length=10)),
                ('energy_wh', models.FloatField(blank=True, null=True)),
                ('cumulated_charge_wh', models.FloatField(default=0.0)),
                ('cumulated_discharge_wh', models.FloatField(default=0.0)),
                ('calibrated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('battery', models.ForeignKey(limit_choices_to={'asset_type': 'BATTERY'}, on_delete=django.db.models.deletion.CASCADE, related_name='battery_states', to='energy_assets.energyasset')),
            ],
            options={
                'verbose_name': 'battery state',
                'verbose_name_plural': 'battery states',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['battery', '-timestamp'], name='energy_asse_battery_843274_idx')],
            },
        ),
    ]
