# Generated by Django 5.0.14 on 2026-07-09 01:33

import apps.devices.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_sensor_energy_asset'),
        ('houses', '0004_house_battery_capacity_kwh_house_pv_capacity_kw'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelayState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.BooleanField(default=True)),
                ('line2', models.BooleanField(default=True)),
                ('line3', models.BooleanField(default=True)),
                ('device_token', models.CharField(default=apps.devices.models._generate_device_token, max_length=64, unique=True)),
                ('last_contact_at', models.DateTimeField(blank=True, null=True)),
                ('last_report', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('house', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relay_state', to='houses.house')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relay_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'relay state',
                'verbose_name_plural': 'relay states',
            },
        ),
    ]
