# Generated by Django 5.0.14 on 2026-07-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_relaystate'),
    ]

    operations = [
        migrations.AddField(
            model_name='relaystate',
            name='last_commanded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
