# Generated by Django 5.0.14 on 2026-07-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_relaystate_last_commanded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='relaystate',
            name='last_measurement_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
