# Generated by Django 5.0.14 on 2026-07-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_relaystate_last_measurement_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='relaystate',
            name='control_mode',
            field=models.CharField(choices=[('MANUAL', 'Manuel'), ('AUTO', 'Automatique (expert)')], default='MANUAL', max_length=10),
        ),
    ]
