# Generated by Django 5.0.14 on 2026-07-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_relaystate_control_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='relaystate',
            name='auto_pending_lines',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relaystate',
            name='auto_pending_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
