# Generated by Django 5.0.14 on 2026-07-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_relaystate_auto_pending_lines_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='relay_line',
            field=models.IntegerField(blank=True, choices=[(1, 'Ligne 1'), (2, 'Ligne 2'), (3, 'Ligne 3')], null=True),
        ),
        migrations.AlterField(
            model_name='relaystate',
            name='control_mode',
            field=models.CharField(choices=[('MANUAL', 'Manuel'), ('ASSISTED', "Assisté (l'expert propose)"), ('AUTO', 'Automatique (expert)')], default='MANUAL', max_length=10),
        ),
    ]
