# Generated by Django 5.0.14 on 2026-07-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_equipment_relay_line_alter_relaystate_control_mode'),
        ('energy_assets', '0001_initial'),
        ('houses', '0005_house_last_activity_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensor',
            options={'ordering': ['house', 'line_number', 'code', 'name']},
        ),
        migrations.AddField(
            model_name='equipment',
            name='load_type',
            field=models.CharField(choices=[('lamp', 'Lampe'), ('socket', 'Prise'), ('appliance', 'Appareil'), ('other', 'Autre')], default='other', max_length=16),
        ),
        migrations.AddField(
            model_name='sensor',
            name='calibrated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='calibration_factor',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='sensor',
            name='calibration_method',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sensor',
            name='calibration_offset',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sensor',
            name='calibration_status',
            field=models.CharField(choices=[('uncalibrated', 'Non calibré'), ('calibrated', 'Calibré'), ('suspect', 'Suspect (à recalibrer)')], default='uncalibrated', max_length=16),
        ),
        migrations.AddField(
            model_name='sensor',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
        migrations.AddField(
            model_name='sensor',
            name='color',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='sensor',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='gpio_pin',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='line_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='priority',
            field=models.CharField(choices=[('CRITICAL', 'Critique (à préserver au maximum)'), ('IMPORTANT', 'Prioritaire'), ('NORMAL', 'Normale'), ('LOW', 'Secondaire'), ('NON_CRITICAL', 'Non prioritaire (délestée en premier)')], default='NORMAL', max_length=15),
        ),
        migrations.AddConstraint(
            model_name='sensor',
            constraint=models.UniqueConstraint(condition=models.Q(('code__gt', '')), fields=('house', 'code'), name='unique_sensor_code_per_house'),
        ),
    ]
