# Generated by Django 5.0.14 on 2026-07-29 17:29

import apps.devices.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_alter_relaystate_control_mode'),
        ('houses', '0005_house_last_activity_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='priority',
            field=models.CharField(choices=[('NON_CRITICAL', 'Non critique'), ('LOW', 'Faible'), ('NORMAL', 'Normale'), ('IMPORTANT', 'Importante'), ('CRITICAL', 'Critique')], default='NORMAL', max_length=15),
        ),
        migrations.CreateModel(
            name='IoTNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ESP32 principal', max_length=80)),
                ('node_type', models.CharField(choices=[('ESP32_MAIN', 'ESP32 principal (lignes AC, relais)'), ('ESP32_DC', 'ESP32 secondaire (bloc continu)'), ('EDGE_GATEWAY', 'Passerelle Edge')], default='ESP32_MAIN', max_length=20)),
                ('device_token', models.CharField(default=apps.devices.models._generate_device_token, max_length=64, unique=True)),
                ('control_mode', models.CharField(choices=[('MANUAL', 'Manuel'), ('ASSISTED', "Assisté (l'expert propose)"), ('AUTOMATIC', 'Automatique (expert)')], default='MANUAL', max_length=16)),
                ('firmware_version', models.CharField(blank=True, max_length=30)),
                ('last_contact_at', models.DateTimeField(blank=True, null=True)),
                ('last_measurement_at', models.DateTimeField(blank=True, null=True)),
                ('last_report', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='houses.house')),
            ],
            options={
                'ordering': ['house', 'node_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=80)),
                ('relay_gpio', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_switchable', models.BooleanField(default=True)),
                ('max_power_w', models.FloatField(blank=True, null=True)),
                ('priority_override', models.CharField(blank=True, choices=[('NON_CRITICAL', 'Non critique'), ('LOW', 'Faible'), ('NORMAL', 'Normale'), ('IMPORTANT', 'Importante'), ('CRITICAL', 'Critique')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='houses.house')),
            ],
            options={
                'ordering': ['house', 'number'],
            },
        ),
        migrations.CreateModel(
            name='LineState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_closed', models.BooleanField(default=True)),
                ('desired_closed', models.BooleanField(default=True)),
                ('pending_since', models.DateTimeField(blank=True, null=True)),
                ('last_commanded_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='devices.line')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='line',
            constraint=models.UniqueConstraint(fields=('house', 'number'), name='ligne_unique_par_maison'),
        ),
    ]
