# Generated by Django 5.0.14 on 2026-07-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_measurement_types_and_sensor_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='measurement_type',
            field=models.CharField(choices=[('production', 'Production'), ('consumption', 'Consumption'), ('battery_soc', 'Battery SoC'), ('voltage', 'Voltage'), ('current', 'Current'), ('power', 'Power'), ('temperature', 'Temperature'), ('luminosity', 'Luminosity'), ('irradiance', 'Irradiance'), ('reactive_power', 'Reactive Power'), ('sub_metering_1', 'Sub-metering 1 (kitchen)'), ('sub_metering_2', 'Sub-metering 2 (laundry)'), ('sub_metering_3', 'Sub-metering 3 (HVAC)'), ('pv_voltage', 'PV Voltage (Vmpp)'), ('pv_current', 'PV Current (Impp)'), ('module_temp', 'Module Temperature'), ('humidity', 'Relative Humidity'), ('air_pressure', 'Air Pressure'), ('wind_speed', 'Wind Speed'), ('wind_direction', 'Wind Direction')], max_length=20),
        ),
    ]
