# Generated by Django 5.0.14 on 2026-07-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0004_alter_measurement_measurement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='measurement_type',
            field=models.CharField(choices=[('production', 'Production'), ('consumption', 'Consumption'), ('battery_soc', 'Battery SoC'), ('voltage', 'Voltage'), ('current', 'Current'), ('power', 'Power'), ('temperature', 'Ambient temperature (weather API)'), ('battery_temp', 'Battery temperature (probe)'), ('panel_temp', 'Solar panel temperature (probe)'), ('luminosity', 'Luminosity'), ('irradiance', 'Irradiance'), ('irradiance_tilt15', 'Irradiance inclinee 15°'), ('irradiance_tilt20', 'Irradiance inclinee 20°'), ('irradiance_east', 'Irradiance orientee Est'), ('irradiance_west', 'Irradiance orientee Ouest'), ('reactive_power', 'Reactive Power'), ('sub_metering_1', 'Sub-metering 1 (kitchen)'), ('sub_metering_2', 'Sub-metering 2 (laundry)'), ('sub_metering_3', 'Sub-metering 3 (HVAC)'), ('pv_voltage', 'PV Voltage (Vmpp)'), ('pv_current', 'PV Current (Impp)'), ('module_temp', 'Module Temperature'), ('humidity', 'Relative Humidity'), ('air_pressure', 'Air Pressure'), ('wind_speed', 'Wind Speed'), ('wind_direction', 'Wind Direction')], max_length=20),
        ),
    ]
