# Generated by Django 5.0.14 on 2026-07-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0005_alter_measurement_measurement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='calibration_factor_used',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='calibration_offset_used',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='quality_status',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='measurement',
            name='raw_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
