# Generated by Django 5.0.14 on 2026-07-29 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0013_peupler_lignes_depuis_relaystate'),
        ('measurements', '0007_alter_measurement_measurement_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('voltage_v', models.FloatField(blank=True, null=True)),
                ('current_a', models.FloatField(blank=True, null=True)),
                ('power_w', models.FloatField(blank=True, null=True)),
                ('relay_closed', models.BooleanField()),
                ('is_measured', models.BooleanField()),
                ('raw_voltage', models.FloatField(blank=True, null=True)),
                ('raw_current', models.FloatField(blank=True, null=True)),
                ('calibration_v', models.FloatField(blank=True, null=True)),
                ('calibration_i', models.FloatField(blank=True, null=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='devices.line')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['line', '-timestamp'], name='measurement_line_id_cc1cfc_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='linereading',
            constraint=models.UniqueConstraint(fields=('line', 'timestamp'), name='un_releve_par_ligne_et_instant'),
        ),
    ]
