# Generated by Django 5.0.14 on 2026-07-31 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_house_last_activity_at'),
        ('measurements', '0011_contraintes_mesure'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(db_index=True)),
                ('valid_at', models.DateTimeField(db_index=True)),
                ('quantity', models.CharField(choices=[('pv_power_w', 'Puissance PV (W)'), ('load_power_w', 'Puissance appelée (W)'), ('grid_voltage_v', 'Tension réseau (V)'), ('grid_current_a', 'Courant total (A)'), ('battery_voltage_v', 'Tension batterie (V)'), ('battery_current_a', 'Courant batterie signé (A)'), ('battery_power_w', 'Puissance batterie (W)'), ('battery_temp_c', 'Température batterie (°C)'), ('battery_soc_pct', 'État de charge (%)'), ('pv_voltage_v', 'Tension PV (V)'), ('pv_current_a', 'Courant PV (A)'), ('module_temp_c', 'Température module (°C)'), ('ambient_temp_c', 'Température ambiante (°C)'), ('irradiance_wm2', 'Irradiance globale (W/m²)'), ('irradiance_tilt15_wm2', 'Irradiance inclinée 15° (W/m²)'), ('irradiance_tilt20_wm2', 'Irradiance inclinée 20° (W/m²)'), ('irradiance_east_wm2', 'Irradiance orientée est (W/m²)'), ('irradiance_west_wm2', 'Irradiance orientée ouest (W/m²)'), ('diffuse_wm2', 'Rayonnement diffus (W/m²)'), ('dni_wm2', 'Irradiance directe normale (W/m²)'), ('humidity_pct', 'Humidité relative (%)'), ('wind_speed_ms', 'Vitesse du vent (m/s)'), ('wind_direction_deg', 'Direction du vent (°)'), ('air_pressure_hpa', 'Pression atmosphérique (hPa)')], max_length=28)),
                ('value', models.FloatField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_forecasts', to='houses.house')),
            ],
            options={
                'ordering': ['-fetched_at', 'valid_at'],
                'indexes': [models.Index(fields=['house', 'valid_at', 'quantity'], name='measurement_house_i_638d13_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='weatherforecast',
            constraint=models.UniqueConstraint(fields=('house', 'quantity', 'fetched_at', 'valid_at'), name='une_prevision_meteo_par_emission_et_echeance'),
        ),
    ]
