# Generated by Django 5.0.14 on 2026-07-31 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0013_peupler_lignes_depuis_relaystate'),
        ('houses', '0005_house_last_activity_at'),
        ('measurements', '0012_prevision_meteo_persistee'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementRollup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(choices=[('pv_power_w', 'Puissance PV (W)'), ('load_power_w', 'Puissance appelée (W)'), ('grid_voltage_v', 'Tension réseau (V)'), ('grid_current_a', 'Courant total (A)'), ('battery_voltage_v', 'Tension batterie (V)'), ('battery_current_a', 'Courant batterie signé (A)'), ('battery_power_w', 'Puissance batterie (W)'), ('battery_temp_c', 'Température batterie (°C)'), ('battery_soc_pct', 'État de charge (%)'), ('pv_voltage_v', 'Tension PV (V)'), ('pv_current_a', 'Courant PV (A)'), ('module_temp_c', 'Température module (°C)'), ('ambient_temp_c', 'Température ambiante (°C)'), ('irradiance_wm2', 'Irradiance globale (W/m²)'), ('irradiance_tilt15_wm2', 'Irradiance inclinée 15° (W/m²)'), ('irradiance_tilt20_wm2', 'Irradiance inclinée 20° (W/m²)'), ('irradiance_east_wm2', 'Irradiance orientée est (W/m²)'), ('irradiance_west_wm2', 'Irradiance orientée ouest (W/m²)'), ('diffuse_wm2', 'Rayonnement diffus (W/m²)'), ('dni_wm2', 'Irradiance directe normale (W/m²)'), ('humidity_pct', 'Humidité relative (%)'), ('wind_speed_ms', 'Vitesse du vent (m/s)'), ('wind_direction_deg', 'Direction du vent (°)'), ('air_pressure_hpa', 'Pression atmosphérique (hPa)')], max_length=28)),
                ('bucket', models.DateTimeField(db_index=True)),
                ('avg_value', models.FloatField()),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('sample_count', models.PositiveIntegerField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_rollups', to='houses.house')),
            ],
            options={
                'ordering': ['-bucket'],
            },
        ),
        migrations.CreateModel(
            name='LineRollup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.DateTimeField(db_index=True)),
                ('avg_power_w', models.FloatField()),
                ('max_power_w', models.FloatField()),
                ('energy_wh', models.FloatField()),
                ('closed_ratio', models.FloatField()),
                ('sample_count', models.PositiveIntegerField()),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollups', to='devices.line')),
            ],
            options={
                'ordering': ['-bucket'],
                'indexes': [models.Index(fields=['line', '-bucket'], name='measurement_line_id_5b8f4d_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='linerollup',
            constraint=models.UniqueConstraint(fields=('line', 'bucket'), name='un_agregat_par_ligne_et_intervalle'),
        ),
        migrations.AddIndex(
            model_name='measurementrollup',
            index=models.Index(fields=['house', 'quantity', '-bucket'], name='measurement_house_i_58e506_idx'),
        ),
        migrations.AddConstraint(
            model_name='measurementrollup',
            constraint=models.UniqueConstraint(fields=('house', 'quantity', 'bucket'), name='un_agregat_par_grandeur_et_intervalle'),
        ),
    ]
