# Generated by Django 5.0.14 on 2026-07-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_energy_assets_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='battery_capacity_kwh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='pv_capacity_kw',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
