# Generated by Django 5.0.14 on 2026-07-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_house_battery_capacity_kwh_house_pv_capacity_kw'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
