# Generated by Django 5.0.14 on 2026-07-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuzzy_engine', '0004_decision_forecast'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='reasoning_trace',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
