# Generated by Django 5.0.14 on 2026-07-31 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0013_peupler_lignes_depuis_relaystate'),
        ('fuzzy_engine', '0005_decision_reasoning_trace'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shed_score', models.FloatField()),
                ('is_blocked', models.BooleanField()),
                ('blocked_reason', models.CharField(blank=True, max_length=40)),
                ('power_w', models.FloatField(blank=True, null=True)),
                ('state_before', models.BooleanField()),
                ('state_desired', models.BooleanField()),
                ('was_applied', models.BooleanField(default=False)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_decisions', to='fuzzy_engine.decision')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='devices.line')),
            ],
            options={
                'ordering': ['line__number'],
            },
        ),
        migrations.AddConstraint(
            model_name='decisionline',
            constraint=models.UniqueConstraint(fields=('decision', 'line'), name='une_conclusion_par_decision_et_ligne'),
        ),
    ]
