; Projet : EMS IoT — Firmware ESP32 3 lignes (prototype mémoire)
; Carte  : ESP32 DevKit (esp32dev)
;
; Commandes utiles :
;   pio run                  -> compile
;   pio run -t upload        -> compile + téléverse
;   pio device monitor       -> moniteur série (115200 bauds)

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags = -Wall
; Si le port n'est pas détecté automatiquement, décommentez et adaptez :
; upload_port = COM5
; monitor_port = COM5
