# Generated by Django 5.0.14 on 2026-07-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0004_imported_model_forecast'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedmodel',
            name='feature_columns',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='importedmodel',
            name='preprocessing_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='importedmodel',
            name='sequence_length',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
