# Generated by Django 5.0.14 on 2026-07-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0005_keras_model_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedmodel',
            name='reference_peak_w',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
